const industries = [
    "Aerospace",
    "Agriculture",
    "Artificial Intelligence",
    "Automotive",
    "Banking",
    "Biotechnology",
    "Brewing",
    "Broadcasting",
    "Building Materials",
    "Chemicals",
    "Civil Engineering",
    "Clothing & Apparel",
    "Commercial Real Estate",
    "Communications Equipment",
    "Construction",
    "Consulting",
    "Consumer Electronics",
    "Consumer Goods",
    "Cosmetics",
    "Dairy",
    "Defense",
    "Digital Media",
    "E-commerce",
    "Education",
    "Electrical Equipment",
    "Electronics",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmental Services",
    "Financial Services",
    "Fisheries",
    "Fitness",
    "Food Production",
    "Forestry",
    "Furniture",
    "Gambling",
    "Gaming",
    "Gas & Oil",
    "Graphic Design",
    "Healthcare",
    "Hospitality",
    "Industrial Automation",
    "Industrial Machinery",
    "Information Technology",
    "Insurance",
    "Investment Banking",
    "Legal Services",
    "Logistics & Supply Chain",
    "Machine Learning",
    "Manufacturing",
    "Marine",
    "Marketing",
    "Medical Devices",
    "Metals",
    "Mining",
    "Motion Pictures and Film",
    "Music",
    "Nanotechnology",
    "Natural Resources",
    "Non-Profit Organization Management",
    "Nuclear Energy",
    "Oil & Energy",
    "Packaging",
    "Paper & Forest Products",
    "Pharmaceuticals",
    "Plastics",
    "Professional Training & Coaching",
    "Public Relations and Communications",
    "Public Safety",
    "Publishing",
    "Railroads",
    "Real Estate",
    "Renewable Energy",
    "Restaurants",
    "Retail",
    "Robotics",
    "Security and Investigations",
    "Semiconductors",
    "Shipbuilding",
    "Software",
    "Solar Power",
    "Space",
    "Sports",
    "Steel",
    "Telecommunications",
    "Textiles",
    "Tobacco",
    "Tourism",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Venture Capital & Private Equity",
    "Veterinary",
    "Video Games",
    "Waste Management",
    "Water Treatment",
    "Web Development",
    "Wind Power",
    "Winemaking",
    "Wireless",
    "Woodworking",
  ];
  
  export default industries;