const jobSearchKeywords = [
    "Software",
    "Hardware",
    "Network",
    "Database",
    "Web Development",
    "Mobile Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cloud Computing",
    "Cybersecurity",
    "UI/UX Design",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "DevOps",
    "Project Management",
    "Quality Assurance",
    "Business Analysis",
    "Product Management",
    "Sales",
    "Marketing",
    "Finance",
    "Human Resources",
    "Customer Support",
    "Operations",
    "Supply Chain",
    "Logistics",
    "Manufacturing",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Environmental Engineering",
    "Aerospace Engineering",
    "Data Analysis",
    "Market Research",
    "Content Writing",
    "Graphic Design",
    "Video Editing",
    "Social Media",
    "Digital Marketing",
    "SEO",
    "E-commerce",
    "Retail",
    "Healthcare",
    "Education",
    "Nonprofit",
    "Government",
    "Consulting",
    "Freelance"
];

export default jobSearchKeywords;