const countries = [
  //"Afghanistan",
  //"Albania",
  //"Algeria",
  //"Andorra",
  //"Angola",
  //"Antigua and Barbuda",
  //"Argentina",
  //"Armenia",
  "Australia",
  //"Austria",
  //"Azerbaijan",
  //"Bahamas",
  //"Bahrain",
  //"Bangladesh",
  //"Barbados",
  //"Belarus",
  //"Belgium",
  //"Belize",
  //"Benin",
  //"Bhutan",
  //"Bolivia",
  //"Bosnia and Herzegovina",
  //"Botswana",
  //"Brazil",
  //"Brunei",
  //"Bulgaria",
  //"Burkina Faso",
  //"Burundi",
  //"Cabo Verde",
  //"Cambodia",
  //"Cameroon",
  "Canada",
  //"Central African Republic",
  //"Chad",
  //"Chile",
  //"China",
  //"Colombia",
  //"Comoros",
  //"Congo",
  //"Costa Rica",
  //"Croatia",
  //"Cuba",
  //"Cyprus",
  //"Czech Republic",
  //"Denmark",
  //"Djibouti",
  //"Dominica",
  //"Dominican Republic",
  //"Ecuador",
  //"Egypt",
  //"El Salvador",
  //"Equatorial Guinea",
  //"Eritrea",
  //"Estonia",
  //"Eswatini",
  //"Ethiopia",
  //"Fiji",
  //"Finland",
  //"France",
  //"Gabon",
  //"Gambia",
  //"Georgia",
  //"Germany",
  //"Ghana",
  //"Greece",
  //"Grenada",
  //"Guatemala",
  //"Guinea",
  //"Guinea-Bissau",
  //"Guyana",
  //"Haiti",
  //"Honduras",
  //"Hungary",
  //"Iceland",
  "India",
  //"Indonesia",
  //"Iran",
  //"Iraq",
  //"Ireland",
  //"Israel",
  //"Italy",
  //"Jamaica",
  //"Japan",
  //"Jordan",
  //"Kazakhstan",
  //"Kenya",
  //"Kiribati",
  //"Kuwait",
  //"Kyrgyzstan",
  //"Laos",
  //"Latvia",
  //"Lebanon",
  //"Lesotho",
  //"Liberia",
  //"Libya",
  //"Liechtenstein",
  //"Lithuania",
  //"Luxembourg",
  //"Madagascar",
  //"Malawi",
  //"Malaysia",
  //"Maldives",
  //"Mali",
  //"Malta",
  //"Marshall Islands",
  //"Mauritania",
  //"Mauritius",
  //"Mexico",
  //"Micronesia",
  //"Moldova",
  //"Monaco",
  //"Mongolia",
  //"Montenegro",
  //"Morocco",
  //"Mozambique",
  //"Myanmar",
  //"Namibia",
  //"Nauru",
  //"Nepal",
  //"Netherlands",
  //"New Zealand",
  //"Nicaragua",
  //"Niger",
  //"Nigeria",
  //"North Korea",
  //"North Macedonia",
  //"Norway",
  //"Oman",
  "Pakistan",
  //"Palau",
  //"Palestine",
  //"Panama",
  //"Papua New Guinea",
  //"Paraguay",
  //"Peru",
  //"Philippines",
  //"Poland",
  //"Portugal",
  //"Qatar",
  //"Romania",
  //"Russia",
  //"Rwanda",
  //"Saint Kitts and Nevis",
  //"Saint Lucia",
  //"Saint Vincent and the Grenadines",
  //"Samoa",
  //"San Marino",
  //"Sao Tome and Principe",
  //"Saudi Arabia",
  //"Senegal",
  //"Serbia",
  //"Seychelles",
  //"Sierra Leone",
  //"Singapore",
  //"Slovakia",
  //"Slovenia",
  //"Solomon Islands",
  //"Somalia",
  //"South Africa",
  //"South Korea",
  //"South Sudan",
  //"Spain",
  //"Sri Lanka",
  //"Sudan",
  //"Suriname",
  //"Sweden",
  //"Switzerland",
  //"Syria",
  //"Taiwan",
  //"Tajikistan",
  //"Tanzania",
  //"Thailand",
  //"Timor-Leste",
  //"Togo",
  //"Tonga",
  //"Trinidad and Tobago",
  //"Tunisia",
  //"Turkey",
  //"Turkmenistan",
  //"Tuvalu",
  //"Uganda",
  //"Ukraine",
  //"United Arab Emirates",
  //"United Kingdom",
  "United States of America",
  //"Uruguay",
  //"Uzbekistan",
  //"Vanuatu",
  //"Vatican City",
  //"Venezuela",
  //"Vietnam",
  //"Yemen",
  //"Zambia",
  //"Zimbabwe",
];

// States and Provinces
const states = {
  Australia: [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
  ],
  India: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  Pakistan: [
    "Balochistan",
    "Gilgit-Baltistan",
    "Jammu and Kashmir",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
  ],
};

const cities = {
  'Canada': {
    'Alberta': ["Calgary", "Edmonton", "Red Deer"],
    "British Columbia": ["Vancouver", "Victoria", "Kelowna"],
    'Ontario': ["Toronto", "Ottawa", "Hamilton"],
    'Quebec': ["Montreal", "Quebec City", "Sherbrooke"],
  },
  'India': {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur"],
    'Karnataka': ["Bengaluru", "Mysuru", "Mangaluru"],
    'Maharashtra': ["Mumbai", "Pune", "Nagpur"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai"],
    'Telangana': ["Hyderabad", "Warangal", "Nizamabad"],
  },
  "United States": {
    'California': ["Los Angeles", "San Francisco", "San Diego"],
    'Florida': ["Miami", "Orlando", "Tampa"],
    "New York": ["New York City", "Buffalo", "Rochester"],
    'Texas': ["Houston", "Dallas", "Austin"],
  },
  'Pakistan': {
    'Punjab': ["Lahore", "Faisalabad", "Rawalpindi"],
    'Sindh': ["Karachi", "Hyderabad", "Sukkur"],
    "Khyber Pakhtunkhwa": ["Peshawar", "Abbottabad", "Mardan"],
    'Balochistan': ["Quetta", "Gwadar", "Turbat"],
  },
  'Australia': {
    "New South Wales": ["Sydney", "Newcastle", "Wollongong"],
    'Victoria': ["Melbourne", "Geelong", "Ballarat"],
    'Queensland': ["Brisbane", "Gold Coast", "Sunshine Coast"],
    "Western Australia": ["Perth", "Mandurah", "Bunbury"],
  },
};


export { countries, states, cities };